apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
      app: mysql
  template:
    metadata:
      labels:
        name: mysql
        app: mysql
    spec:
      containers:
      - name: mysql
        image:  liliangaladima/web-app-mysql:1.0
        ports:
        - containerPort: 3306


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: mysql
spec:
  selector:
    name: mysql
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
