apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    name: web-app
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-app
      app: web-app
  template:
    metadata:
      labels:
        name: web-app
        app: web-app
    spec:
      containers:
      - name: web-app
        image: liliangaladima/web-app:1.0
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    name: web-app
    app: web-app   
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    name: web-app
    app: web-app
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 31001
